### ISSUE TITLE
mark

### ISSUE THREAD

**Issue by wnr** [tomas81508/othello-clojure#10]
Just nu säger ```mark``` i docen: ```If the the board is not marked at the position [x y] then the board is updated with the player marked at [x y]```. Däremot struntar implementationen i om noden är occupied eller ej. Nu använder dessutom till exempel ```move-in-direction``` mark för att ta över redan occupied noder med ett nytt playerId.

1. Antingen ser vi till att ```mark``` fungerar som den beskrivs i doc och gör en ny funktion för att "swappa" spelare. 
2. Vi skulle också kunna uppdatera ```mark``` så att docen beskriver dess verkliga beteende. 

Vet dock inte om jag tycker att mark ska kunna byta playerId på redan occupied noder...

Vad tycker du?

**Comment by tomas81508** [comment]
Documentation is now updated. One should be able to mark at a coordinate that is already occupied.
